### ISSUE TITLE
Document browser compatability

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#109]

**Comment by yakhinvadim** [comment]
I hope it's ok if I reopen this. 

For now, we support evergreen desktop browsers (Edge, Firefox, Opera, Chrome, Safari) and the latest Chrome for Android and iOS Safari. But AFAIK this list is not solid and we might want to add or remove browsers from this list. Since we left the beta, I think it would be good to 
1) discuss and prepare this list
1) test search-ui in the browsers we decide to support
1) update babel-configs
1) add the list to documentation

**Comment by constancecchen** [comment]
One way we could clearly document this as well as have this (mostly) respected by autoprefixer, babel, etc. is using the `browserslist` config in our package.json file: https://github.com/browserslist/browserslist
