### ISSUE TITLE
There should be some way to initiate an initial, empty query when the UI loads.

### ISSUE THREAD

**Issue by JasonStoltz** [elastic/search-ui#194]
Here is an example:

When navigating to the sandbox example at http://localhost:3000, currently, you will see no results.
When navigating to the sandbox example at http://localhosts:3000?q=park, you WILL see results, because a 'q' parameter is being passed and a query is performed.

There should be a way to tell Search UI to also trigger a search and show results in the first example, where no 'q' parameter is passed.

A proposal might be to have something like the following, using a "shouldSearchOnInitialLoad" boolean flag in configuration.

```
<SearchProvider
      config={{
        apiConnector: connector,
        shouldSearchOnInitialLoad: true
      }}
    >
      ...
    </SearchProvider>
```
As Constance points out in a comment below, the corresponding change would need to be made here: https://github.com/elastic/search-ui/blob/master/packages/search-ui/src/SearchDriver.js#L160.
 I believe the logic *may* be as simple as adding an additional condition to check if `shouldSearchOnInitialLoad` is true when deciding whether or not to perform a search.

**Comment by JasonStoltz** [comment]
Hi @delvedor :wave:. You had mentioned this earlier, just wanted to point the issue out to you if you'd like to follow it.

**Comment by constancecchen** [comment]
Just wanted to write down some quick notes from a chat I had with @JasonStoltz about this issue today!

- The area to look at for implementation is probably in [searchDriver.js:160](https://github.com/elastic/search-ui/blob/master/packages/search-ui/src/SearchDriver.js#L160), which checks for a `?q=foobar` query param before initializing with results.

- We should consider whether a 0 Results vs All Results state should be the default. I proposed that All Results is more intuitive as a default, and Jason recommended that we still add a config flag that that adds allows a 0 Results state for users that don't want results to be auto-loaded (an example use-case of this would be Google Maps, which doesn't show search results initially).

**Comment by Kacppian** [comment]
I'll pick this up

**Comment by JasonStoltz** [comment]
@Kacppian Great, let us know if you have any questions.

**Comment by Kacppian** [comment]
Sorry for taking a while on this. I think the line no. mentioned might not be accurate? I think the line no is `175`. Please correct me if I'm wrong. 

The conditional checks if a `valid searchTerm` is present or there's at least 1 filter. We'll be replacing the check for a `valid searchTerm` with the flag `shouldSearchOnInitialLoad`, right?

**Comment by yakhinvadim** [comment]
> Sorry for taking a while on this. I think the line no. mentioned might not be accurate? I think the line no is 175. Please correct me if I'm wrong.

I think you're right, that was a link to the previous version of a file, that didn't include accessibility code

> The conditional checks if a valid searchTerm is present or there's at least 1 filter. We'll be replacing the check for a valid searchTerm with the flag shouldSearchOnInitialLoad, right?

I'm not sure that we should replace it. If we replace it, what would happen if `shouldSearchOnInitialLoad` is set to `false` and searchTerm is present in the URL? My guess is that the search won't happen on the initial load. But we want it to happen since we have a searchTerm in the URL. Does it make sense?

My guess is that should be an additional check:
if `shouldSearchOnInitialLoad` -> trigger search
if not -> run the current if-statement

----------

Also, I have a renaming suggestion here. My expectation from the name `shouldSearchOnInitialLoad` is that if it's set to false, the search will never happen on initial load, but it's wrong - it will happen if I have a query in the URL.
How about we rename it to `alwaysSearchOnInitialLoad`? In that case, if it's set to false, the expectation is "not always, but search in some cases" which is correct. What do y'all think?

**Comment by constancecchen** [comment]
Yep sorry about that! [Line 175](https://github.com/elastic/search-ui/blob/master/packages/search-ui/src/SearchDriver.js#L175) is the right conditional to be looking at.

I agree with @yakhinvadim that `shouldSearchOnInitialLoad` is a bit misleading in name. This issue is about whether we should initially search on **empty** queries - initial existing queries should **always** search (so behavior should remain unchanged from before).

With that in mind, I do like `alwaysSearchOnInitialLoad` personally - I think that's a bit clearer and will be easier to follow branching-wise.

**Comment by Kacppian** [comment]
Agreed. I like the name `alwaysSearchOnInitialLoad` better too. Thanks for the inputs.

**Comment by andersosthus** [comment]
Hi @Kacppian,

Are there any progress on this ? I would like this functionality as well. If you are still working in it, I'll just wait, but if not, I might have time to contribute to this myself.

**Comment by JasonStoltz** [comment]
@andersosthus If you make the contribution I'll be happy to publish it. I think it's a critical feature that is missing right now.

**Comment by Kacppian** [comment]
@andersosthus I did make the changes but the tests were failing. I couldn't finish fixing them. I'm currently going through a hectic work schedule, so couldn't get to working on it.

**Comment by JasonStoltz** [comment]
@Kacppian Do you have a branch you could point us to? Perhaps we can finish the work.

**Comment by andersosthus** [comment]
@JasonStoltz  @Kacppian I've taken the changes and put into my own branch, made sure the tests passed, and submitted PR #392
