### ISSUE TITLE
Add mobile responsiveness

### ISSUE THREAD

**Issue by aznick** [elastic/search-ui#214]
Make the default components more mobile friendly.

We could add components tuned for mobile or add responsive transformations to existing components (with a preference for the former).

With the current styles, the experience is quite poor on mobile:

https://search-ui-stable.netlify.com/

<img width="701" alt="React_App" src="https://user-images.githubusercontent.com/1427475/60988282-4641ce00-a311-11e9-8611-b6b13c24dc44.png">

**Comment by johnbarrierwilson** [comment]
Just a wee bit o' documentation from our discussion/meeting...

We discussed many different possible options for making the filters responsive. The most popular pattern that was discussed was the Wayfair-like flyout with accordions for each individual feature.

In order to get from point-A (conceptual discussions) to point-B (fully implemented responsive filters), I'll be working on:
1) Researching the codebase to see what is do-able
2) Create a few conceptual mockups to help decide on best implementation path

**Comment by JasonStoltz** [comment]
Mentioning the associated PR here, since I don't think it was tagged in the PR itself: https://github.com/elastic/search-ui/pull/344

**Comment by constancecchen** [comment]
No strong feelings either way, but we might want to consider leaving this open since #344 was only meant to be an MVP solution to responsiveness, and doesn't fully implement some nicer UX that users might want to see. I'll defer to @aznick and @johnbarrierwilson on that!

**Comment by JasonStoltz** [comment]
I'll defer to ya'll, but I think we should close this, and if we have more specific mobile UX requirements in the future, we'll open a new issue. This was issue was submitted primarily because the mobile experience was terrible. Since the mobile experience is no longer terrible, I consider this closed.

**Comment by aznick** [comment]
Agreed with @JasonStoltz - issues are meant to track a discrete piece of work or thought. (And closing issues feels good 😎). 

But if you have specific ideas about how we could improve the mobile experience, please feel free to open a new issue @constancecchen! It's a good idea to capture those thoughts and let them marinate, even if it isn't an issue for this sprint.
