### ISSUE TITLE
Remove unused Facets component

### ISSUE THREAD

**Issue by yakhinvadim** [elastic/search-ui#348]
It seems like the `Facets` component in `react-search-ui-views` is not used anywhere in the project or demos, at least when the issue was created. We need to check if it's still not used anywhere and delete the component and all the reference to it.

**Comment by Kacppian** [comment]
Can I take this up?

**Comment by JasonStoltz** [comment]
@Kacppian Since this is a breaking change we flagged this for the 2.0 milestone. We won't be merging PRs for 2.0 for a little while, so I would hold off. If you're looking for an easy first issue, I have flagged some as "good first issue". I can go through and flag some more as well.

Thank you for your interest!

**Comment by Kacppian** [comment]
Thanks for the response! I'll look for other issues then.

**Comment by JasonStoltz** [comment]
@Kacppian Like maybe this one: https://github.com/elastic/search-ui/issues/337 :)

**Comment by Kacppian** [comment]
Awesome! I'll pick that up then. Really appreciate the quick response :)

**Comment by Jfelix61** [comment]
True just checked the codebase; no use of the Facets components anywhere. I will be deleting it in a while.
