### ISSUE TITLE
Dangerously Set Inner Html opens this UI up to XSS from maliciously stored results.

### ISSUE THREAD

**Issue by GrandathePanda** [elastic/search-ui#451]
https://github.com/elastic/search-ui/blob/977175f1b6ca4d0e34339c8e1cdbd16a3de317e6/packages/react-search-ui-views/src/Result.js

This uses set dangerously inner HTML multiple times and receives the params each time from something that comes from the Elasticsearch results. In the case of say a search app that indexes code snippets from a web crawl this opens up this UI to stored XSS attacks pretty easily. 

Even though I typically sanitize the stuff I crawl, others potentially aren't aware and this opens up an attack avenue and it just really shouldn't be used in this context.

**Comment by JasonStoltz** [comment]
@GrandathePanda We do some low-fi escaping here to avoid XSS issues on raw values: https://github.com/elastic/search-ui/blob/977175f1b6ca4d0e34339c8e1cdbd16a3de317e6/packages/react-search-ui-views/src/Result.js#L30.

This view assumes that objects will have data in either a `raw` field or `snippet` field. We are cautious about anything in a raw field and actively escape the values. `snippet` fields are assumed to be safe because in order to have highlights / snippets in the first place.

**Comment by JasonStoltz** [comment]
And to be clear, we *need* to dangerously set inner html in order to display snippets.
