### ISSUE TITLE
Example won't load

### ISSUE THREAD

**Issue by brilhana** [elastic/search-ui#477]
Running `ELASTICSEARCH_HOST=https://@localhost:9300 npm start` from `example/elasticsearch` results in error.

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

**Comment by ratpik** [comment]
I am facing the same issue.

**Comment by ivankozlovcodes** [comment]
I had the same issue. Reset to the previous version. Commit `9147036135f65b8ee4b5523bd9c6890fcd06d214`. It seems to be working fine.

**Comment by JasonStoltz** [comment]
Oh yes, I'm sorry. I know what the issue is here. I updated the `sandbox` example to fix this issue in https://github.com/elastic/search-ui/pull/469/files, but forgot to update this example.

You'd need to run these link commands before starting the project: https://github.com/elastic/search-ui/blob/master/bin/sandbox

```
cd packages/react-search-ui-views
npm link ../../examples/elasticsearch/node_modules/react
cd ../react-search-ui
npm link ../../examples/elasticsearch/node_modules/react
cd ../../examples/sandbox
```

**Comment by JasonStoltz** [comment]
I'll make a startup script like I have for sandbox to make this easier.

**Comment by ivankozlovcodes** [comment]
Not to be a bummer but it does not work event with the steps provided
