### ISSUE TITLE
React Routing

### ISSUE THREAD

**Issue by joerav** [elastic/search-ui#478]
We are getting 503 errors when we refresh the search results page or link to the actual result query directly. Any ideas on how to handle that would be great.

**Comment by richkuz** [comment]
It might not be feasible for your specific scenario, but one potential workaround could be to set `trackUrlState` to false in the [search UI config settings](https://github.com/elastic/search-ui/blob/master/ADVANCED.md#request-state).

**Comment by JasonStoltz** [comment]
Hi @joerav, if you have more details to share about your setup, that would be helpful.

The main thing to be aware of is that Search UI by default uses URL parameters for performing searches and tracking state.

If you are doing query string manipulation yourself on that page, you will need to make sure you turn that off with `trackUrlState: false`.

However, we typically recommend you leave that option on and rely on our routing.

For instance, you could link to your Search Results page built with Search UI from anywhere else on your site with a url like: `/search?q=term`, and we'll populate the query results for you. All user interactions with that page after that are then automatically tracked, so that state is persisted when users press the back button or refresh the page.

**Comment by JasonStoltz** [comment]
Going to close this, I am not able to reproduce and I have not heard back from the OP.
