### ISSUE TITLE
Issue when using local ES instance

### ISSUE THREAD

**Issue by hansley-kowlessur-spoon** [elastic/search-ui#527]
Hi,

I am trying to integrate search-ui using the example provided, however, there are some issues mainly when searching.

I changed the variable names as well as the relevant naming in the following files:

1) `App.js` -> 1. Why  do we need to specify those two fields in the `applyDisjunctiveFaceting`

`const responseJsonWithDisjunctiveFacetCounts = await applyDisjunctiveFaceting(
      responseJson,
      state,
      ["fieldInteger", "fieldText"]
    );`

`  <SearchBox
                    autocompleteMinimumCharacters={3}
                    autocompleteResults={{
                      linkTarget: "_blank",
                      sectionTitle: "Results",
                      titleField: "fieldText",
                      urlField: "_blank",
                      shouldTrackClickThrough: true,
                      clickThroughTags: ["test"]
                    }}
                    autocompleteSuggestions={true}
                  />`

`bodyContent={
                  <Results
                    titleField="fieldText"
                    urlField="_blank"
                    shouldTrackClickThrough={true}
                  />`

2) `BuildRequestFilter.js` -> 1. Does the name in the function below needs to match the aggregation in the `BuildRequest.js`

` export default function buildRequestFilter(filters) { if (!filters) return;  filters = filters.reduce((acc, filter) => {
    if (["aggregationName"].includes(filter.field)) {
      return [...acc, getTermFilter(filter)];
    } return acc; }, []);  if (filters.length < 1) return;  return filters; }`

3) `BuildState.js` -> 1. When searching, the page is returned blank when searching for `Rocky Mountain`

`function getHighlight(hit, fieldName) {
  if (hit._source.fieldText=== "Rocky Mountain" && fieldName === "fieldText") {
    window.hit = hit;
    window.fieldName = fieldName; } if (  !hit.highlight || !hit.highlight[fieldName] || hit.highlight[fieldName].length < 1 ) { return;  }  return hit.highlight[fieldName][0]; }`

4) `buildStateFacets.js`  -> Does the name needs to match the one from the `BuildRequestFilter.js`

`export default function buildStateFacets(aggregations) {
  const aggregationName= getValueFacet(aggregations, "aggregationName"); const facets = { ...(aggregationName&& { aggregationName}) }; if (Object.keys(facets).length > 0) { return facets;  } }`

Thank you for your time and help 👍 

The response is `200` when I checked the command line.

**Comment by JasonStoltz** [comment]
> Why do we need to specify those two fields in the applyDisjunctiveFaceting

Disjunctive faceting is also known as sticky faceting. So basically, when you select an option, all of the other selectable options should remain. The disjunctive faceting we do here is inefficient, a better approach is to use post_filter: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/filter-search-results.html#post-filter. The net effect is the same though.

For the rest of your questions, I am sorry, I am just not sure without performing some debugging. For your questions about filters and aggregations, I'm thinking that yes, they should probably match.

The best I can tell you is to try setting some breakpoints and inspecting the outbound request to see if your Elasticsearch query looks well formed or not.

Sorry, I realize that is probably not very helpful for you, but I'd need more context or a place where I could play with your code (like on a code sandbox) in order to help you further.

**Comment by hansley-kowlessur-spoon** [comment]
Hi,
Thank you for your response and help :)

I did a sandbox, can you please let me know if you have access.

Thanks again.
