### ISSUE TITLE
Custom HTTP Header not being used within OPTIONS (preflight) request

### ISSUE THREAD

**Issue by petericebear** [elastic/search-ui#553]
There is the capability to use the additionalHeaders to add in a custom header like **apikey**. However the preflight OPTIONS requests are not using those additional headers which make the requests block since the apikey header is missing, and the OPTIONS request would get the **Unauthorized** response.

Is there a workaround for it or a fixed solution to include the additionalHeaders also in the OPTIONS requests?

**Comment by richkuz** [comment]
I don't think this is possible. The browser natively generates the OPTIONS request as a preflight CORS check before making the actual App Search request to the server. Browsers only include very specific headers in the preflight check and they are not configurable.

More information here:
https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request
https://stackoverflow.com/questions/13994507/how-do-you-send-a-custom-header-in-a-cors-preflight-options-request

It's possible the customer thinks the issue is with the OPTIONS request, but perhaps it is somewhere else in the request chain.
