### ISSUE TITLE
how to get particular facet values in withSearch HOC?

### ISSUE THREAD

**Issue by yg-yash** [elastic/search-ui#576]
How to get only particular facet all values like for color facets i want all values of colors which are in search engine?

**Comment by JasonStoltz** [comment]
I don't understand your question, but I'll attempt to answer it.

It sounds like you're familiar with how to add a facet, right? And by default, if you have no other filters or search terms applied, the facet will show you "all values of colors with are in a search engine".

If you apply a search term, or a filter on another field, or a filter on the color field, the facet values list will shrink, because facets are always calculated on the current result set, not on the entire engine.

It's not possible to work around this. The best you can do is define the color facet as "disjunctive", which will make it so that the list of facet values doesn't shrink when filtering on a value from that particular facet.

**Comment by yg-yash** [comment]
Thanks for replying Jason,

My concern is how can be use a Facet Component outside search container tage with the help of withSearch Hoc

How will I get data for a certain using withSearch for that custom facet?
