### ISSUE TITLE
Not showing nested object keys for filter 

### ISSUE THREAD

**Issue by PradeepGorule14** [elastic/search-ui#579]
Hi I'm struggling with adding filters that search UI  not  showing the nested object key for filter and I'm trying to add manually in `engine.json` it gives me an error `{"errors":["Facets field cannot facet on token_id"]}` and kindly check the below JSON code

` [
{
"key": "SubToken~e9a55e77304f74a1076ac1919050999360ebefb9e753a363b95c835482eebda8~1",
    "value": {
      "type": "ERC-721 SubToken",
      "token_id": "e9a55e77304f74a1076ac1919050999360ebefb9e753a363b95c835482eebda8",
      "subtoken_id": "e9a55e77304f74a1076ac1919050999360ebefb9e753a363b95c835482eebda8~1",
     }
}
]`

I put that above JSON in my engine but it takes a nested object as a string **i.e value object** due to this it doesn't show token_id in the filter fields

only my point is if I paste JSON in the engine it takes the nested object as an object not a string or  otherwise how can I add my custom filter field in facet

**Comment by JasonStoltz** [comment]
Yeah, unfortunately, App Search does not support nested objects. I think it's saying that it cannot facet on `token_id` because that field is never created. You effectively end up with two fields in your schema if you would index that record...

key: string,
value: string,

The nested object for `value` would get serialized to a JSON string and store in `value`.

**Comment by JasonStoltz** [comment]
There are a number of discuss topics that discuss this: https://discuss.elastic.co/search?q=nested%20category%3A72

Here is one in particular: https://discuss.elastic.co/search?q=nested%20category%3A72
