### ISSUE TITLE
Does it work with React Native?

### ISSUE THREAD

**Issue by mikepng** [elastic/search-ui#599]
I've been trying to make it work with react native but i get an error of '**Browser history needs a DOM**

**Comment by JasonStoltz** [comment]
I've never tried it, but it sounds like [this is the issue](https://github.com/elastic/search-ui/blob/9db35e1a49d95f854b77172f7ccfe540b22a793d/packages/search-ui/src/URLManager.js).

Can you see what happens when you turn [trackUrlState](https://github.com/elastic/search-ui/blob/master/ADVANCED.md#advanced-configuration) off?
