### ISSUE TITLE
nested filters in search ui seem to be unsupported

### ISSUE THREAD

**Issue by dankoz51** [elastic/search-ui#850]
**Describe the bug**
When trying to nest a filter such as in the national parks example
`curl -X GET '[<ENTERPRISE_SEARCH_BASE_URL>](https://www.elastic.co/guide/en/enterprise-search/8.3/endpoints-ref.html#enterprise-search-base-url)/api/as/v1/engines/national-parks-demo/search' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer search-soaewu2ye6uc45dr8mcd54v8' \
-d '{
  "query": "parks",
  "filters": {
    "any": [
      {
        "all": [
          { "states": "California" },
          { "world_heritage_site": "true" }
        ]
      }
    ]
  }
}'`

There is no syntax i can find that works for the search ui filter. The basic filter works but I cant find a way to nest it.
`
const config = {
  searchQuery: {
    facets: buildFacetConfigFromConfig(),
    ...buildSearchOptionsFromConfig(),
    filters : [{field: 'world_heritage_site', values: ["true"]}],
  },
  autocompleteQuery: buildAutocompleteQueryConfig(),
  apiConnector: connector,
  alwaysSearchOnInitialLoad: true
};`

**To Reproduce**

1. Go to the App.js file
2. add the national parks filter
3. run the search ui page
4. See error, An unexpected error occurred: Cannot read properties of undefined (reading 'map')

**Expected behavior**
Page would be filtered by the nested filter

Backend: [App Search]

**Comment by joemcelroy** [comment]
hey @dankoz51 thanks for the bug report. We will look into it soon. 

Context https://discuss.elastic.co/t/complex-filters-in-app-searchui/311922/4

**Comment by joemcelroy** [comment]
Had a look into this issue today. 

What happening is Search UI facets controls what filters are applied. Although you can put in initial filters into `filters` state, this cannot be nested as the facets only assume it's one level deep and work with a simple model of managing filters. If we introduce nesting here, there will likely be issues that arise from facets using the filter state.

What I believe you want is base filters which are nested and computed ahead of time outside of Search UI. One way we can help with this is adding a `baseFilters` property. On request, we combine both the Search UI controlled facet filters with developer provided baseFilters to be performed in the API request.

One way to workaround this issue is implement the beforeSearchCall on the connector [docs](https://docs.elastic.co/search-ui/api/connectors/app-search#options) & [where its called](https://github.com/elastic/search-ui/blob/master/packages/search-ui-app-search-connector/src/AppSearchAPIConnector.ts#L175) and include within the filters property your nested filters before its dispatched to app search API.  

Hope this helps
Joe

**Comment by dankoz51** [comment]
Thanks for the feedback

I am trying to call the beforeSearchCall hook in this way but I dont think its working it does not seem to be firing

Also I did not understand from the "where its called" do i need to modify the where its called function as well?

`const config = {
  searchQuery: {
    facets: buildFacetConfigFromConfig(),
    ...buildSearchOptionsFromConfig(),
    /* filters : [{field: 'world_heritage_site', values: ["true"]}], */
    /*filters: [{
      "any": [
        {
          "all": [
            { "states": "California" },
            { "world_heritage_site": "true" }
          ]
        }
      ]
    }] */
  },
  autocompleteQuery: buildAutocompleteQueryConfig(),
  apiConnector: connector,
  alwaysSearchOnInitialLoad: true,
  beforeSearchCall: (existingSearchOptions, next) => {
    console.log("existingSearchOptions",existingSearchOptions);
    next({
      ...existingSearchOptions,
      group: { field: "title" }
    })
  }
};`

**Comment by joemcelroy** [comment]
Hey @dankoz51 

This hook is implemented on the connector. created an example here https://codesandbox.io/s/thirsty-shape-hyzs3d?file=/src/pages/app-search/index.js:752-847

Hope this helps!

**Comment by ctklainow** [comment]
> What I believe you want is base filters which are nested and computed ahead of time outside of Search UI. One way we can help with this is adding a `baseFilters` property. On request, we combine both the Search UI controlled facet filters with developer provided baseFilters to be performed in the API request.
> 

Hi @joemcelroy, I'm also interested in global nested filters, could you please direct me to where I can find out more about baseFilters? When you say "On request", do you mean it will be applied on a per elastic account basis?

Thanks!

@dankoz51 any luck getting global nested filters to work? I've also tried adding to the config object in `beforeSearchCall` and the initial query works but it breaks my facet filters afterwards (which seems like a common problem on the elastic forums)

**Comment by Katsivelisp** [comment]
Hello @joemcelroy , just to expand on this. How can this be done with an ElasticSearchAPIConnector? 

**beforeSearchCall** is not supported there yet, it seems. Are there any plans? Alternatively, Is there any other way to create facets on nested fields?

**Comment by sergiusticiffw** [comment]
> 

Any news here? I have related issue

**Comment by joemcelroy** [comment]
Hi there, No news, and not planned. 

Alternatives are using www.github.com/searchkit/searchkit which does support nested fields for facets and field results.
