### ISSUE TITLE
Can't get sorting to work

### ISSUE THREAD

**Issue by lynch-a** [elastic/search-ui#932]
(i'm using Search UI with an ElasticSearchAPIConnector and VueJS)

with debug mode enabled, I try to use `setSort()` to sort by a certain field:

`window.searchUI.setSort("created_at", "asc");`

The driver object state looks ok:

```
> window.searchUI
...
"state": {
    "current": 1,
    "filters": [],
    "resultsPerPage": 20,
    "searchTerm": "",
    "sortDirection": "asc",
    "sortField": "created_at",
    "sortList": null,
}
...
```

however, the following network request is sent:
```{
  ...snip...
  "sort": [
    {
      "_score": "desc"
    }
  ]
}
```

my fields are not sorted as requested. what am I missing?

**Comment by jwhollingsworth** [comment]
I just ran into this as well, and if I am reading the code correctly, it is a bug (or at least missing functionality):

I'm thinking it has to do with the elasticsearch connector expecting `state.sortList` to be an array containing the sort (otherwise it defaults the sort to `{"_score": "desc"}`:  https://github.com/elastic/search-ui/blob/main/packages/search-ui-elasticsearch-connector/src/handlers/search/Configuration.ts#L228

But `sortList` isn't set when the field name is passed in to `setSort(sort, sortDirection)` (`sortField` and `sortDirection` are set): https://github.com/elastic/search-ui/blob/main/packages/search-ui/src/actions/setSort.ts#L10

I found this trying to use the react component that call that function with a string, not an array: https://github.com/elastic/search-ui/blob/main/packages/react-search-ui/src/containers/Sorting.tsx#L68

Looks like the app search connector accounts for that possibility, but the elasticsearch one does not https://github.com/elastic/search-ui/blob/main/packages/search-ui-app-search-connector/src/requestAdapters.ts#L61

It would probably work if you called the function like: `window.searchUI.setSort([{field: "created_at", direction: "asc"}])`

**Comment by italodirenzo93** [comment]
Why is this closed? I'm trying to get this to work now and this is still an issue.
